## Exploração dos Dados

### Importação de Bibliotecas Necessárias

In [1]:
# Importar bibliotecas necessárias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

### Importação das Planilhas de Dados

In [2]:
# Carregar os arquivos CSV
df_gf = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GF.csv")
df_gl = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GL.csv")
df_gm = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GM.csv")
df_gp = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GP.csv")
df_gt = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GT.csv")
df_gv = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GV.csv")
df_gw = pd.read_csv("../Grupo com registro entre 07-2024 a 06-2025- GW.csv")

### Divisão de Colunas em Múltiplas Colunas

In [3]:
# Função para dividir colunas únicas em múltiplas colunas
def dividir_colunas(df):        
    # Extrair cabeçalho            
    cabecalho = df.columns[0].split('\t')   
    # Dividir dados
    dados = df.iloc[:, 0].str.split('\t', expand=True) 
    dados.columns = cabecalho
    return dados

# Aplicar a função a cada dataframe
df_gf = dividir_colunas(df_gf)
df_gl = dividir_colunas(df_gl)
df_gm = dividir_colunas(df_gm)
df_gp = dividir_colunas(df_gp)
df_gt = dividir_colunas(df_gt)
df_gv = dividir_colunas(df_gv)
df_gw = dividir_colunas(df_gw)

# Exibir cabeçalhos
display(df_gf.head())
display(df_gl.head())
display(df_gm.head())
display(df_gp.head())
display(df_gt.head())
display(df_gv.head())
display(df_gw.head())

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,41,129,475124351,2025-06-24,REGISTRADO,2025-07-30,360.00,\N,\N,BANCO SANTANDER (BRASIL) S.A.,...,SAO PAULO,\N,\N,CPF,99e02f3b1ca56d979ad615782a839450b7dbabb1559110...,0.00,M,0.11,P,2.00
1,41,79,475937945,2025-06-27,REGISTRADO,2025-07-23,208.08,\N,\N,BANCO SANTANDER (BRASIL) S.A.,...,SAO PAULO,\N,\N,CPF,24d3131aeddadee962b8c6aa27c14e04ba5482743fb76f...,0.00,M,0.06,P,2.00
2,41,85,476378993,2025-06-30,REGISTRADO,2025-07-24,297.02,\N,\N,BANCO SANTANDER (BRASIL) S.A.,...,SANTO ANDRE (SP,\N,\N,CPF,9154dc2de0d3c88cdd77d40a59c2bd77a543fc8dc2ddbb...,0.00,M,0.09,P,2.00
3,41,85,476379036,2025-06-30,REGISTRADO,2025-07-29,297.02,\N,\N,BANCO SANTANDER (BRASIL) S.A.,...,SANTO ANDRE (SP,\N,\N,CPF,9d75dbc691022c487a29db4bbbdd04abc705c31767eff0...,0.00,M,0.09,P,2.00
4,41,85,476379099,2025-06-30,REGISTRADO,2025-07-28,260.55,\N,\N,BANCO SANTANDER (BRASIL) S.A.,...,SANTO ANDRE (SP,\N,\N,CPF,bfd5f75eb99f65b4c61617af3d2a4b4860a74f8e407ed8...,0.00,M,0.08,P,2.00

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,173,554,426309011,2024-11-25,REGISTRADO,2025-12-03,188645.00,\N,\N,ITAU UNIBANCO S.A.,...,CAMPO GRANDE,\N,\N,CNPJ,dc1e3c141c9c7d7408b783c9d4f48bc3721dd9621e4fd4...,0.00,M,62.88,P,2.00
1,173,554,426702880,2024-11-26,REGISTRADO,2025-12-03,69386.15,\N,\N,ITAU UNIBANCO S.A.,...,CAMPO GRANDE,\N,\N,CNPJ,dc1e3c141c9c7d7408b783c9d4f48bc3721dd9621e4fd4...,0.00,M,23.13,P,2.00
2,173,554,427422093,2024-11-28,REGISTRADO,2025-12-03,21717.33,\N,\N,ITAU UNIBANCO S.A.,...,CAMPO GRANDE,\N,\N,CNPJ,dc1e3c141c9c7d7408b783c9d4f48bc3721dd9621e4fd4...,0.00,M,7.24,P,2.00
3,173,554,439264582,2025-01-21,REGISTRADO,2025-05-12,221338.95,\N,\N,ITAU UNIBANCO S.A.,...,BRASILIA,\N,\N,CNPJ,04ffcdcdbb6d616c87ab1c9a5e59586dbc46f95c0e4e98...,0.00,M,73.78,P,2.00
4,173,554,439264583,2025-01-21,REGISTRADO,2025-05-12,110669.49,\N,\N,ITAU UNIBANCO S.A.,...,BRASILIA,\N,\N,CNPJ,04ffcdcdbb6d616c87ab1c9a5e59586dbc46f95c0e4e98...,0.00,M,36.89,P,2.00

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,162,534,379035949,2024-07-01,REGISTRADO,2024-09-26,11032.84,\N,\N,BANCO CITIBANK S.A.,...,BARUERI,\N,\N,CNPJ,56c6c5af9a19fd9b4fe2210bb3b118d5d2e56e05bd8429...,\N,P,9.00,\N,\N
1,162,534,379035950,2024-07-01,REGISTRADO,2024-09-26,7933.38,\N,\N,BANCO CITIBANK S.A.,...,BARUERI,\N,\N,CNPJ,56c6c5af9a19fd9b4fe2210bb3b118d5d2e56e05bd8429...,\N,P,9.00,\N,\N
2,162,534,379035952,2024-07-01,REGISTRADO,2024-09-26,6083.98,\N,\N,BANCO CITIBANK S.A.,...,BARUERI,\N,\N,CNPJ,56c6c5af9a19fd9b4fe2210bb3b118d5d2e56e05bd8429...,\N,P,9.00,\N,\N
3,162,534,379035953,2024-07-01,REGISTRADO,2024-09-26,9862.17,\N,\N,BANCO CITIBANK S.A.,...,BARUERI,\N,\N,CNPJ,56c6c5af9a19fd9b4fe2210bb3b118d5d2e56e05bd8429...,\N,P,9.00,\N,\N
4,162,534,379063314,2024-07-01,REGISTRADO,2024-07-01,24110.85,\N,\N,BANCO DO BRASIL,...,ALFREDO CHAVES,\N,\N,CNPJ,a6ccd8d3d96c8f0a765b231c5d017886ac21c5259608a8...,\N,P,9.00,\N,\N

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,179,563,379629209,2024-07-02,LIQUIDADO,2024-07-03,455.03,2024-07-04,455.03,ITAU UNIBANCO S.A.,...,ESTEIO,1,2024-07-03 10:23:49,CNPJ,9f07f2fc6e6f096bf7fdf43da7930d744331ca6d27ea15...,0.00,M,0.76,\N,\N
1,179,563,379629211,2024-07-02,BAIXADO,2024-07-03,1659.43,\N,\N,ITAU UNIBANCO S.A.,...,MARAGOGI,2,2024-07-04 08:19:37,CNPJ,b8d4972d51fd6957b8b681e4b7a247490d33cd7454adba...,0.00,M,2.77,\N,\N
2,179,563,379629213,2024-07-02,BAIXADO,2024-07-03,67055.81,\N,\N,ITAU UNIBANCO S.A.,...,PALMAS,\N,\N,CNPJ,c59cbc053976d6e12345b23a1e8f11198232aea1188648...,0.00,M,111.76,\N,\N
3,179,563,379629215,2024-07-02,LIQUIDADO,2024-07-03,2976.62,2024-07-04,2976.62,ITAU UNIBANCO S.A.,...,,1,2024-07-03 17:04:26,CNPJ,6951e9e17d57d887362b06bc34f8463f1f09c05ee1a64f...,0.00,M,4.96,\N,\N
4,179,563,379629218,2024-07-02,LIQUIDADO,2024-07-03,1652.40,2024-07-04,1652.40,ITAU UNIBANCO S.A.,...,BELO HORIZONTE,1,2024-07-03 15:23:03,CNPJ,d870ba99aacf0fb806447e69210b4d79d32ea053921dd8...,0.00,M,2.75,\N,\N

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,112,366,379250108,2024-07-01,LIQUIDADO,2024-09-24,692.49,2024-09-25,692.49,BANCO BRADESCO SA,...,SAO PAULO,4,2024-09-24 20:16:44,CPF,bcb14e5f3e741636effe3c3682304a77998f7ead91b55d...,0.00,M,0.55,P,2.00
1,112,366,379250109,2024-07-01,LIQUIDADO,2024-10-24,692.49,2024-10-24,692.49,BANCO BRADESCO SA,...,SAO PAULO,2,2024-10-23 21:58:55,CPF,bcb14e5f3e741636effe3c3682304a77998f7ead91b55d...,0.00,M,0.55,P,2.00
2,112,366,379250110,2024-07-01,LIQUIDADO,2024-11-24,692.49,2024-11-26,692.49,BANCO BRADESCO SA,...,SAO PAULO,4,2024-11-25 18:34:07,CPF,bcb14e5f3e741636effe3c3682304a77998f7ead91b55d...,0.00,M,0.55,P,2.00
3,112,366,379250111,2024-07-01,LIQUIDADO,2024-12-24,692.49,2024-12-26,692.49,BANCO BRADESCO SA,...,SAO PAULO,2,2024-12-24 19:37:21,CPF,bcb14e5f3e741636effe3c3682304a77998f7ead91b55d...,0.00,M,0.55,P,2.00
4,112,366,379250112,2024-07-01,BAIXADO,2025-01-24,692.49,\N,\N,BANCO BRADESCO SA,...,SAO PAULO,4,2025-02-19 14:36:48,CPF,bcb14e5f3e741636effe3c3682304a77998f7ead91b55d...,0.00,M,0.55,P,2.00

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,67,213,379258486,2024-07-01,LIQUIDADO,2024-07-03,3523.46,2024-07-03,3523.46,BANCO BRADESCO SA,...,,1,2024-07-02 10:04:18,CNPJ,0af3e87aae13146b69111742d09937ed393139a2432371...,0.00,P,6.00,P,2.00
1,67,213,379339644,2024-07-01,LIQUIDADO,2024-08-08,515.00,2024-08-09,515.00,BANCO BRADESCO SA,...,,\N,\N,CNPJ,66536580868885fda6094c34b82afddc2af18daf3c8c86...,0.00,P,6.00,P,2.00
2,67,213,379339645,2024-07-01,LIQUIDADO,2024-08-09,577.76,2024-08-12,577.76,BANCO BRADESCO SA,...,,\N,\N,CNPJ,6e9788f27d01d939f3245d7eb84e4ed14bcb2170e458e5...,0.00,P,6.00,P,2.00
3,67,213,379339646,2024-07-01,LIQUIDADO,2024-08-09,440.76,2024-08-12,440.76,BANCO BRADESCO SA,...,,\N,\N,CNPJ,513848b111e8b41dc6283c4e89d49e5171a072038d56c8...,0.00,P,6.00,P,2.00
4,67,213,379339647,2024-07-01,LIQUIDADO,2024-08-08,272.00,2024-08-09,272.00,BANCO BRADESCO SA,...,,\N,\N,CNPJ,da32dd7e7ca4c02a4c0750b0c4f1b6043167c62f8e30d7...,0.00,P,6.00,P,2.00

,id_grupo,id_beneficiario,Numero_do_boleto,data_inclusao,status_boleto,data_vencto,vl_boleto,dt_pagto,vl_pagto,banco,...,pagador_cidade,qtd_acessos_pagador,pagador_dt_ultimo_acesso,pagador_cnpjcpf,pagador_inscricao_hash,valor_abatimento,tipo_juros,juros,tipo_multa,multa
0,212,658,380217446,2024-07-03,BAIXADO,2024-07-29,8528.52,\N,\N,BANCO DO BRASIL,...,Mage,3,2024-08-10 15:58:02,CNPJ,01fa7845e68846b4f804f5df66393cf022c5266cfaf688...,0.00,M,2.84,P,10.00
1,212,658,380217447,2024-07-03,LIQUIDADO,2024-08-27,8528.52,2024-08-23,8528.52,BANCO DO BRASIL,...,Mage,1,2024-08-09 16:35:15,CNPJ,01fa7845e68846b4f804f5df66393cf022c5266cfaf688...,0.00,M,2.84,P,10.00
2,212,658,380217448,2024-07-03,LIQUIDADO,2024-09-26,8528.52,2024-09-23,8528.52,BANCO DO BRASIL,...,Mage,3,2024-09-10 14:30:58,CNPJ,01fa7845e68846b4f804f5df66393cf022c5266cfaf688...,0.00,M,2.84,P,10.00
3,212,658,380217449,2024-07-03,LIQUIDADO,2024-10-28,8528.52,2024-10-24,8528.52,BANCO DO BRASIL,...,Mage,2,2024-09-11 11:54:13,CNPJ,01fa7845e68846b4f804f5df66393cf022c5266cfaf688...,0.00,M,2.84,P,10.00
4,212,658,380217450,2024-07-03,LIQUIDADO,2024-11-25,8528.52,2024-11-26,8528.52,BANCO DO BRASIL,...,Mage,2,2024-09-11 11:55:11,CNPJ,01fa7845e68846b4f804f5df66393cf022c5266cfaf688...,0.00,M,2.84,P,10.00

### Conversão de Tipos de Dados

In [ ]:
# Definir colunas numéricas e categóricas
colunas_numericas = ['id_grupo', 'id_pagador', 'id_beneficiario', 'Numero_do_boleto', 'vl_boleto', 'vl_pagto', 'juros']
colunas_categoricas = ['status_boleto', 'pagador_cep', 'banco', 'tipo_juros', 'pagador_cidade', 'data_inclusao', 'data_vencto', 'dt_pagto']

# Função para converter tipos de colunas
def converter_tipos(df, colunas, tipo):
    for coluna in colunas:
        if coluna in df.columns:    
            # Substituir '\N' por NaN
            df[coluna] = df[coluna].replace('\\N', np.nan)  
            if tipo == 'float':
                # Converter para float
                df[coluna] = pd.to_numeric(df[coluna], errors='coerce')  
            elif tipo == 'datetime':
                # Converter para datetime
                df[coluna] = pd.to_datetime(df[coluna], errors='coerce')  
            else:
                # Converter para o tipo especificado
                df[coluna] = df[coluna].astype(tipo)

# Aplicar conversões
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    converter_tipos(df, colunas_numericas, 'float')
    converter_tipos(df, colunas_categoricas, 'category')

# Exibir informações dos dataframes
display(df_gf.info())
display(df_gl.info())
display(df_gm.info())
display(df_gp.info())
display(df_gt.info())
display(df_gv.info())
display(df_gw.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_grupo                  20433 non-null  int64
 1   id_beneficiario           20433 non-null  int64
 2   Numero_do_boleto          20433 non-null  int64
 3   data_inclusao             20433 non-null  category
 4   status_boleto             20433 non-null  category
 5   data_vencto               20433 non-null  category
 6   vl_boleto                 20433 non-null  float64
 7   dt_pagto                  14215 non-null  category
 8   vl_pagto                  14215 non-null  float64
 9   banco                     20433 non-null  category
 10  id_pagador                20433 non-null  int64
 11  pagador_cep               20433 non-null  category
 12  pagador_cidade            20433 non-null  category
 13  qtd_acessos_pagador       20433 non-null  object
 14  pagador_dt_ultimo_acesso  20433 non-null  object
 15  pagador_cnpjcpf           20433 non-null  object
 16  pagador_inscricao_hash    20433 non-null  object
 17  valor_abatimento          20433 non-null  object
 18  tipo_juros                20433 non-null  category
 19  juros                     20433 non-null  float64
 20  tipo_multa                20433 non-null  object
 21  multa                     20433 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 2.5+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9890 entries, 0 to 9889
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_grupo                  9890 non-null   int64
 1   id_beneficiario           9890 non-null   int64
 2   Numero_do_boleto          9890 non-null   int64
 3   data_inclusao             9890 non-null   category
 4   status_boleto             9890 non-null   category
 5   data_vencto               9890 non-null   category
 6   vl_boleto                 9890 non-null   float64
 7   dt_pagto                  8940 non-null   category
 8   vl_pagto                  8940 non-null   float64
 9   banco                     9890 non-null   category
 10  id_pagador                9890 non-null   int64
 11  pagador_cep               9890 non-null   category
 12  pagador_cidade            9890 non-null   category
 13  qtd_acessos_pagador       9890 non-null   object
 14  pagador_dt_ultimo_acesso  9890 non-null   object
 15  pagador_cnpjcpf           9890 non-null   object
 16  pagador_inscricao_hash    9890 non-null   object
 17  valor_abatimento          9890 non-null   object
 18  tipo_juros                9890 non-null   category
 19  juros                     9890 non-null   float64
 20  tipo_multa                9890 non-null   object
 21  multa                     9890 non-null   object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 1.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349965 entries, 0 to 349964
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_grupo                  349965 non-null  int64
 1   id_beneficiario           349965 non-null  int64
 2   Numero_do_boleto          349965 non-null  int64
 3   data_inclusao             349965 non-null  category
 4   status_boleto             349965 non-null  category
 5   data_vencto               349965 non-null  category
 6   vl_boleto                 349965 non-null  float64
 7   dt_pagto                  195414 non-null  category
 8   vl_pagto                  195414 non-null  float64
 9   banco                     349965 non-null  category
 10  id_pagador                349965 non-null  int64
 11  pagador_cep               349965 non-null  category
 12  pagador_cidade            349965 non-null  category
 13  qtd_acessos_pagador       349965 non-null  object
 14  pagador_dt_ultimo_acesso  349965 non-null  object
 15  pagador_cnpjcpf           349965 non-null  object
 16  pagador_inscricao_hash    349965 non-null  object
 17  valor_abatimento          349965 non-null  object
 18  tipo_juros                349965 non-null  category
 19  juros                     349965 non-null  float64
 20  tipo_multa                349965 non-null  object
 21  multa                     349965 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 42.5+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403965 entries, 0 to 403964
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_grupo                  403965 non-null  int64
 1   id_beneficiario           403965 non-null  int64
 2   Numero_do_boleto          403965 non-null  int64
 3   data_inclusao             403965 non-null  category
 4   status_boleto             403965 non-null  category
 5   data_vencto               403965 non-null  category
 6   vl_boleto                 403965 non-null  float64
 7   dt_pagto                  332973 non-null  category
 8   vl_pagto                  333008 non-null  float64
 9   banco                     403965 non-null  category
 10  id_pagador                403965 non-null  int64
 11  pagador_cep               403965 non-null  category
 12  pagador_cidade            403965 non-null  category
 13  qtd_acessos_pagador       403965 non-null  object
 14  pagador_dt_ultimo_acesso  403965 non-null  object
 15  pagador_cnpjcpf           403965 non-null  object
 16  pagador_inscricao_hash    403965 non-null  object
 17  valor_abatimento          403965 non-null  object
 18  tipo_juros                403965 non-null  category
 19  juros                     403965 non-null  float64
 20  tipo_multa                403965 non-null  object
 21  multa                     403965 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 48.6+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439044 entries, 0 to 439043
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_grupo                  439044 non-null  int64
 1   id_beneficiario           439044 non-null  int64
 2   Numero_do_boleto          439044 non-null  int64
 3   data_inclusao             439044 non-null  category
 4   status_boleto             439044 non-null  category
 5   data_vencto               439044 non-null  category
 6   vl_boleto                 439044 non-null  float64
 7   dt_pagto                  137081 non-null  category
 8   vl_pagto                  137081 non-null  float64
 9   banco                     439044 non-null  category
 10  id_pagador                439044 non-null  int64
 11  pagador_cep               438966 non-null  category
 12  pagador_cidade            426869 non-null  category
 13  qtd_acessos_pagador       439044 non-null  object
 14  pagador_dt_ultimo_acesso  439044 non-null  object
 15  pagador_cnpjcpf           439044 non-null  object
 16  pagador_inscricao_hash    439044 non-null  object
 17  valor_abatimento          439044 non-null  object
 18  tipo_juros                439044 non-null  category
 19  juros                     439044 non-null  float64
 20  tipo_multa                439044 non-null  object
 21  multa                     439044 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 53.1+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279477 entries, 0 to 279476
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_grupo                  279477 non-null  int64
 1   id_beneficiario           279477 non-null  int64
 2   Numero_do_boleto          279477 non-null  int64
 3   data_inclusao             279477 non-null  category
 4   status_boleto             279477 non-null  category
 5   data_vencto               279477 non-null  category
 6   vl_boleto                 279477 non-null  float64
 7   dt_pagto                  259034 non-null  category
 8   vl_pagto                  259034 non-null  float64
 9   banco                     279477 non-null  category
 10  id_pagador                279477 non-null  int64
 11  pagador_cep               279477 non-null  category
 12  pagador_cidade            279474 non-null  category
 13  qtd_acessos_pagador       279477 non-null  object
 14  pagador_dt_ultimo_acesso  279477 non-null  object
 15  pagador_cnpjcpf           279477 non-null  object
 16  pagador_inscricao_hash    279477 non-null  object
 17  valor_abatimento          279477 non-null  object
 18  tipo_juros                279477 non-null  category
 19  juros                     279477 non-null  float64
 20  tipo_multa                279477 non-null  object
 21  multa                     279477 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 33.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132655 entries, 0 to 132654
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_grupo                  132655 non-null  int64
 1   id_beneficiario           132655 non-null  int64
 2   Numero_do_boleto          132655 non-null  int64
 3   data_inclusao             132655 non-null  category
 4   status_boleto             132655 non-null  category
 5   data_vencto               132655 non-null  category
 6   vl_boleto                 132655 non-null  float64
 7   dt_pagto                  55988 non-null   category
 8   vl_pagto                  58801 non-null   float64
 9   banco                     132655 non-null  category
 10  id_pagador                132655 non-null  int64
 11  pagador_cep               132654 non-null  category
 12  pagador_cidade            132636 non-null  category
 13  qtd_acessos_pagador       132655 non-null  object
 14  pagador_dt_ultimo_acesso  132655 non-null  object
 15  pagador_cnpjcpf           132655 non-null  object
 16  pagador_inscricao_hash    132655 non-null  object
 17  valor_abatimento          132655 non-null  object
 18  tipo_juros                132655 non-null  category
 19  juros                     132655 non-null  float64
 20  tipo_multa                132655 non-null  object
 21  multa                     132655 non-null  object
dtypes: category(8), float64(3), int64(4), object(7)
memory usage: 16.1+ MB

None

## Tratamento de Valores Ausentes

In [ ]:
# Remover colunas irrelevantes e preencher valores ausentes
colunas_para_remover_geral = [
    'tipo_multa',
    'multa'
]

for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    # Remover colunas que existem no dataframe atual
    colunas_existentes_para_remover = [col for col in colunas_para_remover_geral if col in df.columns]
    df.drop(columns=colunas_existentes_para_remover, inplace=True)

    if 'vl_pagto' in df.columns:
        # Preencher valores ausentes com 0
        df['vl_pagto'] = df['vl_pagto'].fillna(0)  
    if 'pagador_cidade' in df.columns:
        # Garantir que a coluna seja categórica antes de adicionar a nova categoria
        df['pagador_cidade'] = df['pagador_cidade'].astype('category')
        df['pagador_cidade'] = df['pagador_cidade'].cat.add_categories('Desconhecido').fillna('Desconhecido')

    for coluna_data in ['data_inclusao', 'data_vencto', 'dt_pagto']:
        if coluna_data in df.columns:
            # Converter para datetime, substituindo '\N' por NaT e depois preenchendo NaT com NaT
            df[coluna_data] = pd.to_datetime(df[coluna_data].replace('\\N', np.nan), errors='coerce').fillna(pd.NaT)

## Estatística Descritiva dos Dados

In [ ]:
# Exibir estatísticas descritivas para cada dataframe
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    display(df.describe())

## Identificação e Tratamento de Outliers

In [ ]:
# Aplicar capping para tratar outliers
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    for coluna in colunas_numericas:
        if coluna in df.columns:
            # Calcular limites para capping
            Q1 = df[coluna].quantile(0.25)
            Q3 = df[coluna].quantile(0.75)
            IQR = Q3 - Q1
            limite_inferior = Q1 - 1.5 * IQR
            limite_superior = Q3 + 1.5 * IQR
            # Aplicar capping
            df[coluna] = np.where(df[coluna] < limite_inferior, limite_inferior, df[coluna])
            df[coluna] = np.where(df[coluna] > limite_superior, limite_superior, df[coluna])

## Codificação de Variáveis Categóricas

In [ ]:
# Aplicar one-hot encoding nas variáveis categóricas
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    colunas_para_codificar = [col for col in colunas_categoricas if col in df.columns]
    df = pd.get_dummies(df, columns=colunas_para_codificar, dummy_na=False)

## Normalização de Variáveis Numéricas

In [ ]:
# Normalizar colunas numéricas usando StandardScaler
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    scaler = StandardScaler()
    colunas_para_normalizar = [col for col in colunas_numericas if col in df.columns]
    if colunas_para_normalizar:
        df[colunas_para_normalizar] = scaler.fit_transform(df[colunas_para_normalizar])

## DataFrames Resultantes Após Normalização

In [ ]:
# Exibir o cabeçalho (head) de cada dataframe após a normalização
for df in [df_gf, df_gl, df_gm, df_gp, df_gt, df_gv, df_gw]:
    display(df.head())

## Gráficos

In [7]:
df_gf['data_vencto'] = pd.to_datetime(df_gf['data_vencto'], errors='coerce', dayfirst=True)
df_gf['data_inclusao'] = pd.to_datetime(df_gf['data_inclusao'], errors='coerce', dayfirst=True)

dataVen = df_gf['data_vencto']
dataInc = df_gf['data_inclusao']
Datas = dataVen - dataInc
TipoData = Datas.unique()
print(TipoData)

<TimedeltaArray>
['36 days', '26 days', '24 days', '29 days', '28 days', '23 days', '21 days',
 '19 days', '17 days', '20 days',  '9 days', '15 days',  '7 days', '18 days',
 '25 days', '33 days', '27 days', '30 days',  '6 days', '31 days', '16 days',
 '22 days', '11 days',  '1 days',  '5 days', '32 days', '13 days',  '0 days',
 '10 days', '14 days',  '3 days', '12 days',  '8 days',  '4 days', '55 days',
 '51 days', '48 days', '46 days', '44 days', '45 days', '47 days', '42 days',
 '41 days', '43 days', '34 days', '40 days', '50 days', '39 days',  '2 days',
 '-1 days', '53 days', '37 days']
Length: 52, dtype: timedelta64[ns]